[package]
name = "engine"
version = "0.1.0"
authors = ["Norbert <norbertbodziony@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority-queue = "1.0.0" 

[[bin]]
name = "main"
path = "src/bin/main.rs"
